notifications:
  commits: commits@stormcrawler.apache.org
  issues: dev@stormcrawler.apache.org
  pullrequests: dev@stormcrawler.apache.org

publish:
  whoami: asf-site

staging:
  whoami:  asf-staging