# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

notifications:
  commits: commits@storm.apache.org
  issues: issues@storm.apache.org
  pullrequests: dev@storm.apache.org

publish:
  whoami: asf-site

github:
  description: "Source for the Apache Storm web site"
  homepage: https://storm.apache.org/
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false
   
