services:
  local:
    build: .
    profiles: ["local"]
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    environment:
      JEKYLL_ENV: development
    command: sh -c "bundle install && bundle exec jekyll serve --watch --force_polling --incremental --host 0.0.0.0 --config _config-local.yml"

  build:
    build: .
    profiles: ["build"]
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    command: sh -c "bundle install && bundle exec jekyll build"

volumes:
  bundle_cache:
    driver: local
